In [1]:
import numpy as np

In [3]:
from sklearn import datasets

In [4]:
mydata = datasets.load_iris()

In [5]:
mydata.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [7]:
type(mydata.data)

numpy.ndarray

In [ ]:
mydata.DESCR

In [8]:
mydata.data.shape

(150, 4)

In [9]:
mydata.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
np.unique(mydata.target)

array([0, 1, 2])

In [11]:
mydata.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='<U10')

In [12]:
mydata.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
X_input=mydata.data

In [14]:
Y_out=mydata.target

In [55]:
X_train=X_input[:-10]

In [56]:
X_train.shape

(140, 4)

In [57]:
X_test=X_input[-10:]

In [58]:
X_test.shape

(10, 4)

In [59]:
Y_train=Y_out[:-10]

In [60]:
Y_test=Y_out[-10:]

In [61]:
Y_train.shape

(140,)

In [62]:
Y_test.shape

(10,)

In [63]:
from sklearn.neighbors import KNeighborsClassifier

In [64]:
myknn=KNeighborsClassifier(n_neighbors=3)

In [65]:
mymodel=myknn.fit(X_train,Y_train)

In [66]:
X_test

array([[ 6.7,  3.1,  5.6,  2.4],
       [ 6.9,  3.1,  5.1,  2.3],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 6.8,  3.2,  5.9,  2.3],
       [ 6.7,  3.3,  5.7,  2.5],
       [ 6.7,  3. ,  5.2,  2.3],
       [ 6.3,  2.5,  5. ,  1.9],
       [ 6.5,  3. ,  5.2,  2. ],
       [ 6.2,  3.4,  5.4,  2.3],
       [ 5.9,  3. ,  5.1,  1.8]])

In [67]:
Yp=mymodel.predict(X_test)

In [68]:
Y_test

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [69]:
Yp

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [70]:
from sklearn import metrics

In [71]:
metrics.accuracy_score(Y_test,Yp)

1.0

In [72]:
mymodel.predict([[3.8,4.1,3.5,1.7]])

array([1])

In [73]:
mydata.target_names[1]

'versicolor'